CREATE TABLE DOCUMENT(
    ID BIGINT AUTO_INCREMENT,
    CATEGORY_ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    URL VARCHAR(255)
)

CREATE DOCUMENT_HISTORY(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_ID BIGINT NOT NULL,
    FILES VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL
)