CREATE TABLE user(
    ID BIGINT AUTO_INCREMENT,
    ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    MOBILE VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    BIRTHDAY TIMESTAMP NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP,
    STATUS_ID BIGINT NOT NULL
);